-- Schema complet France - Orléans 30km + Loiret + France
create extension if not exists "pgcrypto";
create table profiles (id uuid primary key references auth.users(id) on delete cascade, email text, full_name text, city_default text default 'Orléans', plan text default 'starter' check (plan in ('starter','pro','agence')), created_at timestamp default now());
create table zones (id uuid default gen_random_uuid() primary key, owner_id uuid references profiles(id) on delete cascade, name text not null, zone_type text check (zone_type in ('rayon','departement','region','france')), center_lat float, center_lng float, center_city text, radius_km int check (radius_km between 1 and 100), department_code text, region_name text, property_types text[] default array['maison','appart'], transaction_types text[] default array['vente'], particulier_only boolean default true, is_active boolean default true, last_scrape_at timestamp, annonces_count int default 0, created_at timestamp default now());
create table pige_cache (id uuid default gen_random_uuid() primary key, zone_hash text unique, zone_id uuid references zones(id), source text, raw_data jsonb, annonces_count int, scraped_at timestamp default now(), expires_at timestamp default now() + interval '24 hours');
create table pige_listings (id uuid default gen_random_uuid() primary key, zone_id uuid references zones(id) on delete cascade, owner_id uuid references profiles(id) on delete cascade, source text, external_id text, title text, address text, city text, department_code text, price int, price_m2 int, surface int, property_type text, days_online int, price_drop int, price_drop_percent float, url text, score_vendeur int, lat float, lng float, is_pro boolean default false, created_at timestamp default now(), unique(external_id,zone_id));
create table properties (id uuid default gen_random_uuid() primary key, owner_id uuid references profiles(id), zone_id uuid references zones(id), address text not null, lat float, lng float, statut text default 'a_faire' check (statut in ('a_faire','boite','porte_a_porte','pas_interesse','a_recontacter','courrier_envoye','qr_scanne','vendeur_chaud','rdv','mandat')), consent_rgpd boolean default false, contact_autorise boolean default false, last_contact date, created_at timestamp default now());
alter table zones enable row level security; alter table pige_listings enable row level security; alter table properties enable row level security;
create policy "owner zones" on zones for all using (owner_id = auth.uid()); create policy "owner pige" on pige_listings for all using (owner_id = auth.uid()); create policy "owner props" on properties for all using (owner_id = auth.uid());
create index idx_zones_owner on zones(owner_id); create index idx_pige_cache_hash on pige_cache(zone_hash);
